### ISSUE TITLE
phone-haze数据集

### ISSUE THREAD

**Issue by zsyan97** [fanjunkai1/NSDNet#2]
作者您好，请问您文章中提到的phone-haze数据集是如何构建的，可否分享一下，感谢！

**Comment by hello2377** [comment]
Thank you for your interest in our work! Sorry for my late reply.
For details of the PhoneHazy dataset, please refer to Appendix A of the article (https://arxiv.org/pdf/2303.04940).

**Comment by fanjunkai1** [comment]
Thank you for your interest in our work! Sorry for my late reply.
For details of the PhoneHazy dataset, please refer to Appendix A of the article (https://arxiv.org/pdf/2303.04940).

**Comment by fanjunkai1** [comment]
> 作者您好，请问您文章中提到的phone-haze数据集是如何构建的，可否分享一下，感谢！

Thank you for your interest in our work! Sorry for my late reply.
For details of the PhoneHazy dataset, please refer to Appendix A of the article (https://arxiv.org/pdf/2303.04940).
